apiVersion: v1
kind: Service
metadata:
  name: productsnpapiservice
spec:
  type: NodePort
  selector:
    app: productsapi 
  ports:
    - name: productsnpapiservice
      protocol: TCP
      port: 8080
      targetPort: 80
